### ISSUE TITLE
When will fortunejack work again?

### ISSUE THREAD

**Issue by mrgreedy911** [seuntie900/DiceBot#57]
When will fortunejack work again?

**Comment by Seuntjie900** [comment]
Probably never. I've been in contact with them now and then about it. The response from them is always they'll escalate the issue and then I never hear from them again.

Pressure from players will probably be a big driving force to get it supported again. If you and other players put pressure on fortunejack to help me get the issues fixed, it's more likely to get solved than just me asking over and over again.
