### ISSUE TITLE
Can't login on stake 

### ISSUE THREAD

**Issue by Skilat** [seuntie900/DiceBot#85]
![image](https://github.com/Seuntjie900/DiceBot/assets/39880529/e0f89737-e79f-4447-b12c-d2973b4bc69c)
I got this error when I try to login on stake. No issues until ver. 4.28 but now I can't login at all. I tried everything mentionned in the help section

**Comment by Seuntjie900** [comment]
There is no official version 4 of the bot. The latest official version of the bot is 3.4.15 or Kry Games Bot Alpha 006
